import { ImgBestSellerOne, ImgBestSellerTwo } from "@/assets/images";

export const CartData = [
    {
      id: 1,
      image: ImgBestSellerOne,
      category: "Vegetables",
      brand: "Mackdonalds",
      title: "Butternut squash",
      weight: "1kg",
      price: 5.23,
      isNew: true,
      isFavorite: false,
    },
    {
      id: 2,
      image: ImgBestSellerTwo,
      category: "Fruits",
      brand: "FreshFarm",
      title: "Red Apple",
      weight: "1kg",
      price: 3.99,
      isNew: false,
      isFavorite: true,
    },
    {
      id: 3,
      image: ImgBestSellerOne,
      category: "Dairy",
      brand: "Milko",
      title: "Full Cream Milk",
      weight: "1L",
      price: 2.75,
      isNew: false,
      isFavorite: false,
    },
    {
      id: 4,
      image: ImgBestSellerTwo,
      category: "Poultry",
      brand: "Golden Farm",
      title: "Brown Eggs",
      weight: "12pcs",
      price: 4.2,
      isNew: true,
      isFavorite: false,
    },
    {
      id: 5,
      image: ImgBestSellerOne,
      category: "Dairy",
      brand: "Cheezy",
      title: "Cheddar Cheese",
      weight: "200g",
      price: 6.49,
      isNew: false,
      isFavorite: true,
    },
    {
      id: 6,
      image: ImgBestSellerTwo,
      category: "Bakery",
      brand: "Bakers House",
      title: "Whole Wheat Bread",
      weight: "400g",
      price: 2.35,
      isNew: true,
      isFavorite: false,
    },
  ];